# Generated by Django 5.1.4 on 2024-12-29 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('mutuelle', models.CharField(blank=True, max_length=100, null=True)),
                ('personne_a_contacter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bilan', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilanBiologique', to='api.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.dpi'),
        ),
        migrations.CreateModel(
            name='ExamenBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=255)),
                ('resultat', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='api.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dpi',
            name='medecin_traitant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='api.medecin'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyseBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(max_length=255)),
                ('resultat', models.CharField(max_length=255)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_biologiques', to='api.dpi')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_biologiques', to='api.laborantin')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatExamenImagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagerie/%Y/%m/%d/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_imagerie', to='api.dpi')),
                ('radiologue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_imagerie', to='api.radiologue')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_soin', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='api.dpi')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='api.infirmier')),
            ],
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resultat_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu', to='api.resultatexamenimagerie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resultat_examen',), name='unique_compte_rendu_per_resultat')],
            },
        ),
    ]
