# Generated by Django 5.1.4 on 2024-12-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='api.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=255)),
                ('resultat', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
                ('date_examen', models.DateTimeField()),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='api.bilanbiologique')),
            ],
        ),
    ]
