# Generated by Django 5.1.4 on 2024-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultation_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/radiology/'),
        ),
    ]
