# Generated by Django 5.1.4 on 2024-12-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bilanradiologique_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenbiologique',
            name='date_examen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='unite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
