# Generated by Django 5.1.4 on 2024-12-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
