# Generated by Django 5.1.4 on 2024-12-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenbiologique',
            name='resultat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
