# Generated by Django 5.1.4 on 2024-12-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ordonnance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonnance',
            old_name='texte',
            new_name='text',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
